[
    {
        "name": "grass",
        "path": "grass.png",
        "transparent": true,
        "door": false,
        "killer": false,
    },
    {
        "name": "stone",
        "path": "stone.png",
        "transparent": false,
        "door": false,
        "leader": false,
        "killer": false,
    },
    {
        "name": "dirt",
        "path": "dirt.png",
        "transparent": false,
        "door": false,
        "leader": false,
        "killer": false,
    },
    {
        "name": "cobblestone",
        "path": "cobblestone.png",
        "transparent": false,
        "door": false,
        "leader": false,
        "killer": false,
    },
    {
        "name": "bedrock",
        "path": "bedrock.png",
        "transparent": false,
        "door": false,
        "leader": false,
        "killer": false,
    },
    {
        "name": "air",
        "path": "air.png",
        "transparent": true,
        "door": false,
        "leader": false,
        "killer": false,
    },
    {
        "name": "door",
        "path": "door.png",
        "transparent": true,
        "door": true,
        "leader": false,
        "killer": false,
    },
    {
        "name": "leader",
        "path": "leader.png",
        "transparent": true,
        "door": false,
        "leader": true,
        "killer": false,
    }
]